### ISSUE TITLE
Some styles miss in critical file output

### ISSUE THREAD

**Issue by mrtuvn** [bobmotor/magento-2-gulp#24] opened 2021-03-04 09:50 UTC
Is this a normal behavior ? After run gulp task gen critical i will expected file get all neccessary styles need for render page without jank or unstyles. In  a reality i tested this with default luma theme of magento (not use default magento file critical) .
https://github.com/magento/magento2/blob/2.4-develop/app/design/frontend/Magento/luma/web/css/critical.css

I found this file critical.css generated miss some styles relate (breadcrumbs). This link on top below nav. User while load page may notices some breaks in this component because styles not available soon enough

Here is my screenshot for reference (when page loading)

Expected results
Page should load at early stage without missing styles (look like jank or broken)

Actually results
Some area miss styles can see when page loading! 

![Screenshot from 2021-03-04 16-49-35](https://user-images.githubusercontent.com/1908873/109945340-b6347180-7d09-11eb-928e-1689391321f9.png)

**Comment by volodymyr-lisniak** [comment] 2021-03-04 13:42
@mrtuvn Could you show me your `criticalConfig.js` file?

**Comment by mrtuvn** [comment] 2021-03-04 14:00
of course here you go 
![Screenshot from 2021-03-04 20-59-15](https://user-images.githubusercontent.com/1908873/109974898-9f534680-7d2c-11eb-9e12-907b021dece8.png)

**Comment by mrtuvn** [comment] 2021-03-04 14:03
module.exports = {
    hostname: 'app.contribution',
    generic: 'test',
    useHttp2: true
};

file local.js
Not sure you can reproduce same like mine

MAYBE OUT OF SCOPE OF THIS REPORT
Used ubuntu 18.10
My enviroment running in docker (nginx,php,mysql,node)
node v10.22.0
npm v6.14.6

When run critical task inside dockeri got issue like this

![Screenshot from 2021-03-04 21-11-06](https://user-images.githubusercontent.com/1908873/109976532-73d15b80-7d2e-11eb-9093-53e0d5a2d271.png)


So i have to run outside of it (right in project root folder contain my project)
From host machine (outside)
node v10.24.0
npm 6.14.11

![Screenshot from 2021-03-04 21-16-20](https://user-images.githubusercontent.com/1908873/109977067-02de7380-7d2f-11eb-9291-0938392b8781.png)

**Comment by volodymyr-lisniak** [comment] 2021-03-05 09:26
@mrtuvn Maybe you have broken the page at the moment when you run `gulp critical --luma`?

Here are my examples with different configs (`criticalConfig.js`)

```
module.exports = {
    ...
    height: 130,
    ...
};
```
`critical.css` `11KB`

<img width="1440" alt="130" src="https://user-images.githubusercontent.com/9715167/110094348-63f45e80-7da4-11eb-924a-1dbfa4b731ec.png">

```
module.exports = {
    ...
    height: 900,
    ...
};
```
`critical.css` `16KB`

<img width="1440" alt="900" src="https://user-images.githubusercontent.com/9715167/110094362-68b91280-7da4-11eb-853e-2d155c687b95.png">

**Comment by mrtuvn** [comment] 2021-03-05 09:38
i have tested with luma install with sample data inside docker but somehow critical task gulp can't run inside that. So i have to run from outside host machine. Task run complete without anyproblem but the final result seem miss some styles

My expect is file output critical should be have all neccessary styles need for render page without jank. I don't have retouch/modify that file after file generated

Your results pretty much close like me

**Comment by volodymyr-lisniak** [comment] 2021-03-05 09:50
@mrtuvn Does `critical.css` size change with different settings in your case?
```
module.exports = {
    ...
    height: 900,
    ...
};
```
`critical.css` `16KB`

```
module.exports = {
    ...
    height: 130,
    ...
};
```
`critical.css` `11KB`

**Comment by mrtuvn** [comment] 2021-03-05 09:57
Yes i think value will be difference

**Comment by volodymyr-lisniak** [comment] 2021-03-05 10:15
I think this problem is caused by the page you are tested. If you check the styles on the home page everything should be ok because `critical.css` created for exactly this page.
```
module.exports = {
    ...
    url: `${ptotocol}://${localConfig.hostname}.${localConfig.generic}/`,
    ...
};
```
As a solution, I can recommend creating critical styles only for the header (`130px` in the case of the Luma theme). And for the rest of the page, you could use the loader to hide the unstyled content before the main styles are loaded.

**Comment by volodymyr-lisniak** [comment] 2021-03-05 10:58
@mrtuvn Does it satisfy your request? Can I close the issue?

**Comment by mrtuvn** [comment] 2021-03-05 11:21
OK i think we can close it now. Thanks you

**Closed as completed** 2021-03-05 11:22 UTC
